name: checkout-action
description: GitHub Action for checking out a repository. (Simplified actions/checkout alternative that does not depend on Node.js.)

# Note:
# - inputs.* should be manually mapped to INPUT_* due to https://github.com/actions/runner/issues/665
# - Use GITHUB_*/RUNNER_* instead of github.*/runner.* due to https://github.com/actions/runner/issues/2185
runs:
  using: composite
  steps:
    - run: |
        set -eu
        if ! command -v sh >/dev/null; then
          printf '::error::checkout-action requires a POSIX shell (sh)\n'
          exit 1
        fi
      shell: sh
      if: runner.os	== 'Linux'
    - run: sh "${GITHUB_ACTION_PATH:?}/main.sh"
      shell: sh
